# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90804bd4543e079be7be8756dd0e4562f33679609fc1d9a5f6a6e095fc4e243b5d51021993cece0f5459324cf92c5206ddc9675fba7478b268630a1d47c77894

test:
  secret_key_base: 6f050b42435bf363df9c1d579cf0b0e63dc81d1cf46e0d45bba0bb8286eab2ea6541b587e92cd31e32411da0298165b41500360b5289fcaf82552b2dd6f3deb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
